import { Link } from "react-router-dom";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { env } from "../lib/env";

export function Home() {
  return (
    <section className="space-y-8">
      <header className="space-y-4 rounded-2xl border border-[#f1ddc9] bg-[#fff7ec] p-6 sm:p-8">
        <p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#d94828]">Starter Template</p>
        <h1 className="text-3xl font-bold tracking-tight text-[#26170e] sm:text-4xl">{env.appName}</h1>
        <p className="max-w-2xl text-sm leading-relaxed text-[#6f5b4a] sm:text-base">
          This is a lightweight starter page intended to be customized or fully regenerated by AI.
        </p>
        <div className="flex flex-wrap gap-3">
          <Button asChild size="lg" className="bg-[#ff6b4a] text-white hover:bg-[#d94828]">
            <Link to="/">Primary Action</Link>
          </Button>
          <Button asChild variant="outline" size="lg" className="border-[#e7cdb4] bg-[#fffaf2] text-[#26170e] hover:bg-[#ffe7cf]">
            <Link to="/">Secondary Action</Link>
          </Button>
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card className="border-[#f1ddc9] bg-[#fffaf2]">
          <CardHeader>
            <CardTitle className="text-xl text-[#26170e]">Section One</CardTitle>
            <CardDescription className="text-[#6f5b4a]">Use this area for your main value proposition.</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-[#6f5b4a]">Replace with generated content, components, and layouts.</CardContent>
        </Card>

        <Card className="border-[#f1ddc9] bg-[#fffaf2]">
          <CardHeader>
            <CardTitle className="text-xl text-[#26170e]">Section Two</CardTitle>
            <CardDescription className="text-[#6f5b4a]">Keep only the blocks you need for your final flow.</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-[#6f5b4a]">This starter is intentionally minimal and easy to iterate.</CardContent>
        </Card>

        <Card className="border-[#f1ddc9] bg-[#fffaf2]">
          <CardHeader>
            <CardTitle className="text-xl text-[#26170e]">Section Three</CardTitle>
            <CardDescription className="text-[#6f5b4a]">Connect your data and routes from here.</CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-[#6f5b4a]">Update API calls in <code>src/lib/api.ts</code> when integrating backend services.</CardContent>
        </Card>
      </div>
    </section>
  );
}
